// Exemple de données
export const cities = [
   {
      id: '1',
      name: 'Paris',
      image: 'https://www.allsuites.com/wp-content/uploads/2024/09/Paris.jpg',
   },
   {
      id: '2',
      name: 'Tokyo',
      image: 'https://cdn-blog.superprof.com/blog_fr/wp-content/uploads/2018/03/palais-imperial-tokyo.jpg',
   },
   {
      id: '3',
      name: 'New York',
      image: 'https://cdn-imgix.headout.com/tour/30357/TOUR-IMAGE/6cdcf542-452d-4897-beed-76cf68f154e4-1act-de005e04-05d9-4715-96b0-6a089d5c3460.jpg?auto=format&w=1222.3999999999999&h=687.6&q=90&ar=16%3A9&crop=faces&fit=crop',
   },
   {
      id: '4',
      name: 'Londres',
      image: 'https://media.clondres.com/resize/uploads/sites/5/2018/03/big-ben-londres-696x478.jpg?format=auto',
   },
   {
      id: '5',
      name: 'Rome',
      image: 'https://www.webcity.fr/wp-content/uploads/2017/11/monument-rome-1.jpg',
   },
   {
      id: '6',
      name: 'Barcelone',
      image: 'https://jacheteenespagne.com/wp-content/uploads/2024/06/0bda496746574de3ac1ec5c68616272b-1.jpg',
   },
   {
      id: '7',
      name: 'Paris',
      image: 'https://www.secretdeparis.com/blog/wp-content/uploads/2025/04/eiffel-tower-975004_1280.jpg',
   },
   {
      id: '8',
      name: 'Tokyo',
      image: 'https://cdn-blog.superprof.com/blog_fr/wp-content/uploads/2018/03/palais-imperial-tokyo.jpg',
   },
   {
      id: '9',
      name: 'New York',
      image: 'https://cdn-imgix.headout.com/tour/30357/TOUR-IMAGE/6cdcf542-452d-4897-beed-76cf68f154e4-1act-de005e04-05d9-4715-96b0-6a089d5c3460.jpg?auto=format&w=1222.3999999999999&h=687.6&q=90&ar=16%3A9&crop=faces&fit=crop',
   },
   {
      id: '10',
      name: 'Londres',
      image: 'https://media.clondres.com/resize/uploads/sites/5/2018/03/big-ben-londres-696x478.jpg?format=auto',
   },
   {
      id: '11',
      name: 'Rome',
      image: 'https://www.webcity.fr/wp-content/uploads/2017/11/monument-rome-1.jpg',
   },
   {
      id: '12',
      name: 'Barcelone',
      image: 'https://jacheteenespagne.com/wp-content/uploads/2024/06/0bda496746574de3ac1ec5c68616272b-1.jpg',
   },
]

export const buildings = [
   {
      id: '1',
      cityId: '1',
      name: 'Musée du Louvre',
      image: 'https://i.notretemps.com/2000x1125/smart/2023/10/19/musee-du-louvre.jpg',
      city: 'Paris',
      country: 'France',
      constructionYear: '1793',
      architect: 'Multiples architectes',
      style: 'Classique',
   },
   {
      id: '10',
      cityId: '1',
      name: 'Tour Eiffel',
      image: 'https://www.secretdeparis.com/blog/wp-content/uploads/2025/04/eiffel-tower-975004_1280.jpg',
      city: 'Paris',
      country: 'France',
      constructionYear: '1889',
      architect: 'Gustave Eiffel',
      style: 'Industrielle',
   },
   {
      id: '2',
      cityId: '2',
      name: 'Sanctuaire Asakusa',
      image: 'https://media.istockphoto.com/id/1329537420/fr/photo/tokyo-japon-27-octobre-2017-tokyo-japon-horizon-de-la-ville-au-temple-asakusa.jpg?s=612x612&w=0&k=20&c=0mRZPy-eg603K8FPB7k_O73e7tqHLv4PIDjWIKcXXH4=',
      city: 'Tokyo',
      country: 'Japon',
      constructionYear: '645',
      architect: 'Inconnu',
      style: 'Traditionnelle japonaise',
   },
   {
      id: '11',
      cityId: '2',
      name: 'Tokyo Tower',
      image: 'https://byfood.b-cdn.net/api/public/assets/59153/content?optimizer=image',
      city: 'Tokyo',
      country: 'Japon',
      constructionYear: '1958',
      architect: 'Tachū Naitō',
      style: 'Moderne',
   },
   {
      id: '3',
      cityId: '3',
      name: 'Empire State Building',
      image: 'https://cdn.calendarz.com/uploads/events/may/1/41113/empire-state-building_compressed.jpg',
      city: 'New York',
      country: 'États-Unis',
      constructionYear: '1931',
      architect: 'Shreve, Lamb & Harmon',
      style: 'Art déco',
   },
   {
      id: '12',
      cityId: '3',
      name: 'Statue de la Liberté',
      image: 'https://cdn.sortiraparis.com/images/80/66131/1184658-connaissez-vous-les-origines-parisiennes-de-la-statue-de-la-liberte-de-new-york.jpg',
      city: 'New York',
      country: 'États-Unis',
      constructionYear: '1886',
      architect: 'Frédéric Auguste Bartholdi',
      style: 'Néo-classique',
   },
   {
      id: '13',
      cityId: '4',
      name: 'Buckingham Palace',
      image: 'https://cdn-imgix.headout.com/media/images/31a4bf553f447246bf5bd92b00cb1707-12286-london-changing-of-the-guard-tour-with-optional-buckingham-palace-entry-11.jpg',
      city: 'Londres',
      country: 'Royaume-Uni',
      constructionYear: '1703',
      architect: 'William Winde',
      style: 'Néo-classique',
   },
   {
      id: '14',
      cityId: '4',
      name: 'Tower Bridge',
      image: 'https://cdn.britannica.com/35/156335-050-62245FCA/Tower-Bridge-River-Thames-London.jpg',
      city: 'Londres',
      country: 'Royaume-Uni',
      constructionYear: '1894',
      architect: 'Horace Jones',
      style: 'Néogothique',
   },
   {
      id: '5',
      cityId: '5',
      name: 'Fontaine de Trevi',
      image: 'https://as2.ftcdn.net/v2/jpg/01/21/87/47/1000_F_121874733_ObMVN0dprpejLPmvkQumpLRvxOWOI7sW.jpg',
      city: 'Rome',
      country: 'Italie',
      constructionYear: '1762',
      architect: 'Nicola Salvi',
      style: 'Baroque',
   },
   {
      id: '15',
      cityId: '5',
      name: 'Le Panthéon',
      image: 'https://voyageur-attitude.fr/wp-content/uploads/Le-Pantheon-1024x644.jpg',
      city: 'Rome',
      country: 'Italie',
      constructionYear: '125',
      architect: 'Apollodore de Damas',
      style: 'Antique',
   },
   {
      id: '6',
      cityId: '6',
      name: 'Sagrada Família',
      image: 'https://lelephant-larevue.fr/wp-content/uploads/2018/03/%CE%A3%CE%B1%CE%B3%CF%81%CE%B1%CC%81%CE%B4%CE%B1_%CE%A6%CE%B1%CE%BC%CE%B9%CC%81%CE%BB%CE%B9%CE%B1_2941.jpg',
      city: 'Barcelone',
      country: 'Espagne',
      constructionYear: '1882',
      architect: 'Antoni Gaudí',
      style: 'Modernisme catalan',
   },
   {
      id: '16',
      cityId: '6',
      name: 'Parc Güell',
      image: 'https://www.guidesulysse.com/images/destinations/iStock-534846887.jpg',
      city: 'Barcelone',
      country: 'Espagne',
      constructionYear: '1900',
      architect: 'Antoni Gaudí',
      style: 'Modernisme catalan',
   },
]

export const categories = [
   { id: '1', name: 'Musées', icon: '🏛' },
   { id: '2', name: 'Ponts', icon: '🌉' },
   { id: '3', name: 'Religieux', icon: '⛪' },
   { id: '4', name: 'Gratte-ciels', icon: '🏙' },
   { id: '5', name: 'Châteaux & palais', icon: '🏰' },
   { id: '6', name: 'Bâtiments civils', icon: '🏢' },
]
