// Exemple de données
export const cities = [
   {
      id: '1',
      name: 'Paris',
      image: 'https://www.allsuites.com/wp-content/uploads/2024/09/Paris.jpg',
   },
   {
      id: '2',
      name: 'Tokyo',
      image: 'https://cdn-blog.superprof.com/blog_fr/wp-content/uploads/2018/03/palais-imperial-tokyo.jpg',
   },
   {
      id: '3',
      name: 'New York',
      image: 'https://cdn-imgix.headout.com/tour/30357/TOUR-IMAGE/6cdcf542-452d-4897-beed-76cf68f154e4-1act-de005e04-05d9-4715-96b0-6a089d5c3460.jpg?auto=format&w=1222.3999999999999&h=687.6&q=90&ar=16%3A9&crop=faces&fit=crop',
   },
   {
      id: '4',
      name: 'Londres',
      image: 'https://media.clondres.com/resize/uploads/sites/5/2018/03/big-ben-londres-696x478.jpg?format=auto',
   },
   {
      id: '5',
      name: 'Rome',
      image: 'https://www.webcity.fr/wp-content/uploads/2017/11/monument-rome-1.jpg',
   },
   {
      id: '6',
      name: 'Barcelone',
      image: 'https://jacheteenespagne.com/wp-content/uploads/2024/06/0bda496746574de3ac1ec5c68616272b-1.jpg',
   },
   {
      id: '7',
      name: 'Paris',
      image: 'https://www.secretdeparis.com/blog/wp-content/uploads/2025/04/eiffel-tower-975004_1280.jpg',
   },
   {
      id: '8',
      name: 'Tokyo',
      image: 'https://cdn-blog.superprof.com/blog_fr/wp-content/uploads/2018/03/palais-imperial-tokyo.jpg',
   },
   {
      id: '9',
      name: 'New York',
      image: 'https://cdn-imgix.headout.com/tour/30357/TOUR-IMAGE/6cdcf542-452d-4897-beed-76cf68f154e4-1act-de005e04-05d9-4715-96b0-6a089d5c3460.jpg?auto=format&w=1222.3999999999999&h=687.6&q=90&ar=16%3A9&crop=faces&fit=crop',
   },
   {
      id: '10',
      name: 'Londres',
      image: 'https://media.clondres.com/resize/uploads/sites/5/2018/03/big-ben-londres-696x478.jpg?format=auto',
   },
   {
      id: '11',
      name: 'Rome',
      image: 'https://www.webcity.fr/wp-content/uploads/2017/11/monument-rome-1.jpg',
   },
   {
      id: '12',
      name: 'Barcelone',
      image: 'https://jacheteenespagne.com/wp-content/uploads/2024/06/0bda496746574de3ac1ec5c68616272b-1.jpg',
   },
]

export const buildings = [
   {
      id: '1',
      cityId: '1',
      name: 'Musée du Louvre',
      image: 'https://i.notretemps.com/2000x1125/smart/2023/10/19/musee-du-louvre.jpg',
      city: 'Paris',
      country: 'France',
      constructionYear: '1793',
      architect: 'Multiples architectes',
      style: 'Classique',
      description:
         "Ancien palais royal transformé en musée à la Révolution française, le Musée du Louvre est aujourd'hui l'un des plus grands et des plus célèbres musées du monde. Situé au cœur de Paris, il abrite des collections exceptionnelles couvrant plusieurs millénaires d'histoire et de civilisations. De l'Égypte antique à l'art occidental du XIXᵉ siècle, ses galeries rassemblent des œuvres emblématiques comme la Joconde ou la Vénus de Milo. Son architecture mêle héritage classique et modernité, notamment avec la pyramide de verre inaugurée en 1989. Symbole culturel majeur, le Louvre attire chaque année des millions de visiteurs venus admirer la richesse artistique qu'il conserve.",
      ticketPrice: 17,
      visitDuration: '2h-4h',
      booking: 'Recommandée',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:00', end: '18:00' }],
            mardi: [],
            mercredi: [{ start: '09:00', end: '21:00' }],
            jeudi: [{ start: '09:00', end: '18:00' }],
            vendredi: [{ start: '09:00', end: '21:00' }],
            samedi: [{ start: '09:00', end: '18:00' }],
            dimanche: [{ start: '09:00', end: '18:00' }],
         },
         note: 'Fermé le mardi. Dernière admission 1h avant la fermeture, évacuation 30 min avant.',
      },
   },
   {
      id: '10',
      cityId: '1',
      name: 'Tour Eiffel',
      image: 'https://www.secretdeparis.com/blog/wp-content/uploads/2025/04/eiffel-tower-975004_1280.jpg',
      city: 'Paris',
      country: 'France',
      constructionYear: '1889',
      architect: 'Gustave Eiffel',
      style: 'Industrielle',
      description:
         "Construite pour l'Exposition universelle de 1889, la Tour Eiffel est devenue le symbole emblématique de Paris et de la France. Imaginée par l'ingénieur Gustave Eiffel, elle devait initialement être démontée après l'événement et illustrer le savoir-faire industriel français de la fin du XIXᵉ siècle. Haute de 324 mètres, elle fut pendant plus de quarante ans la plus haute structure du monde. Entièrement réalisée en fer puddlé, elle incarne l'audace technique et l'innovation de son époque. D'abord vivement critiquée, elle est aujourd'hui l'un des monuments les plus visités au monde et offre des panoramas exceptionnels sur la capitale.",
      ticketPrice: 29,
      visitDuration: '1h30-2h30',
      booking: 'Obligatoire',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:30', end: '23:00' }],
            mardi: [{ start: '09:30', end: '23:00' }],
            mercredi: [{ start: '09:30', end: '23:00' }],
            jeudi: [{ start: '09:30', end: '23:00' }],
            vendredi: [{ start: '09:30', end: '23:00' }],
            samedi: [{ start: '09:30', end: '23:00' }],
            dimanche: [{ start: '09:30', end: '23:00' }],
         },
         note: 'Horaires susceptibles de varier selon la saison et l’affluence. Vérifier le jour même si besoin.',
      },
   },
   {
      id: '2',
      cityId: '2',
      name: 'Sanctuaire Asakusa',
      image: 'https://media.istockphoto.com/id/1329537420/fr/photo/tokyo-japon-27-octobre-2017-tokyo-japon-horizon-de-la-ville-au-temple-asakusa.jpg?s=612x612&w=0&k=20&c=0mRZPy-eg603K8FPB7k_O73e7tqHLv4PIDjWIKcXXH4=',
      city: 'Tokyo',
      country: 'Japon',
      constructionYear: '645',
      architect: 'Inconnu',
      style: 'Traditionnelle japonaise',
      description:
         "Fondé au VIIᵉ siècle, le sanctuaire d'Asakusa, également connu sous le nom de Sensō-ji, est l'un des plus anciens et des plus vénérés temples bouddhistes de Tokyo. Reconstruit à plusieurs reprises au fil des siècles, il demeure un symbole spirituel majeur de la capitale japonaise. Son imposante porte Kaminarimon et sa pagode à cinq étages attirent fidèles et visiteurs venus découvrir l'architecture traditionnelle japonaise. Entouré d'une rue commerçante animée, le sanctuaire incarne l'équilibre entre héritage religieux et vie urbaine moderne. Lieu de festivals et de cérémonies, il conserve une atmosphère solennelle tout en restant profondément ancré dans le quotidien tokyoïte.",
      ticketPrice: 0,
      visitDuration: '45-60 min',
      booking: 'Non requis',
      accessStatus: 'Accès libre',
      accessiblePRM: false,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '06:00', end: '17:00' }],
            mardi: [{ start: '06:00', end: '17:00' }],
            mercredi: [{ start: '06:00', end: '17:00' }],
            jeudi: [{ start: '06:00', end: '17:00' }],
            vendredi: [{ start: '06:00', end: '17:00' }],
            samedi: [{ start: '06:00', end: '17:00' }],
            dimanche: [{ start: '06:00', end: '17:00' }],
         },
         note: 'En général : le hall principal est ~06:00–17:00 (peut ouvrir à 06:30 d’octobre à mars). Les abords/enceinte sont accessibles en continu.',
      },
   },
   {
      id: '11',
      cityId: '2',
      name: 'Tokyo Tower',
      image: 'https://byfood.b-cdn.net/api/public/assets/59153/content?optimizer=image',
      city: 'Tokyo',
      country: 'Japon',
      constructionYear: '1958',
      architect: 'Tachū Naitō',
      style: 'Moderne',
      description:
         "Inaugurée en 1958, la Tokyo Tower s'inspire de la Tour Eiffel tout en affirmant une identité propre au Japon d'après-guerre. Haute de 333 mètres, elle fut construite pour soutenir les antennes de diffusion télévisuelle et symboliser le renouveau économique du pays. Peinte en blanc et orange pour répondre aux normes aériennes, elle domine le paysage tokyoïte et offre des plateformes panoramiques spectaculaires. Mélange de fonctionnalité technique et d'esthétique moderne, la tour est devenue un repère iconique de la capitale. Elle demeure aujourd'hui un lieu touristique incontournable, particulièrement appréciée au coucher du soleil et de nuit.",
      ticketPrice: 9,
      visitDuration: '1h-1h30',
      booking: 'Recommandée',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:00', end: '23:00' }],
            mardi: [{ start: '09:00', end: '23:00' }],
            mercredi: [{ start: '09:00', end: '23:00' }],
            jeudi: [{ start: '09:00', end: '23:00' }],
            vendredi: [{ start: '09:00', end: '23:00' }],
            samedi: [{ start: '09:00', end: '23:00' }],
            dimanche: [{ start: '09:00', end: '23:00' }],
         },
         note: 'Main Deck : dernière admission ~22:30. Top Deck Tour : ~09:00–22:45 (dernier tour ~22:15).',
      },
   },
   {
      id: '3',
      cityId: '3',
      name: 'Empire State Building',
      image: 'https://cdn.calendarz.com/uploads/events/may/1/41113/empire-state-building_compressed.jpg',
      city: 'New York',
      country: 'États-Unis',
      constructionYear: '1931',
      architect: 'Shreve, Lamb & Harmon',
      style: 'Art déco',
      description:
         "Achevé en 1931 au cœur de Manhattan, l'Empire State Building est l'un des gratte-ciel les plus célèbres au monde. Construit en pleine Grande Dépression, il incarnait l'ambition et la résilience américaines. Son style Art déco, caractérisé par des lignes élancées et des détails géométriques, en fait un chef-d'œuvre architectural du XXᵉ siècle. Pendant près de quarante ans, il fut le plus haut immeuble du monde. Ses observatoires offrent une vue panoramique exceptionnelle sur New York et ses environs. Véritable icône de la skyline new-yorkaise, il demeure un symbole fort de modernité et de puissance urbaine.",
      ticketPrice: 41,
      visitDuration: '1h-2h',
      booking: 'Recommandée',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Variable',
         days: {
            lundi: [],
            mardi: [],
            mercredi: [],
            jeudi: [],
            vendredi: [],
            samedi: [],
            dimanche: [],
         },
         note: 'Horaires variables selon les dates (calendrier officiel). Exemple : du 6 jan au 12 fév : 10:00–21:00 (entrée ferme 20:00).',
      },
   },
   {
      id: '12',
      cityId: '3',
      name: 'Statue de la Liberté',
      image: 'https://cdn.sortiraparis.com/images/80/66131/1184658-connaissez-vous-les-origines-parisiennes-de-la-statue-de-la-liberte-de-new-york.jpg',
      city: 'New York',
      country: 'États-Unis',
      constructionYear: '1886',
      architect: 'Frédéric Auguste Bartholdi',
      style: 'Néo-classique',
      description:
         "Offerte par la France aux États-Unis en 1886, la Statue de la Liberté est devenue l'un des symboles les plus puissants de liberté et de démocratie. Conçue par le sculpteur Frédéric Auguste Bartholdi avec une structure interne imaginée par Gustave Eiffel, elle accueille les visiteurs à l'entrée du port de New York. Haute de 93 mètres avec son piédestal, elle représente la déesse romaine Libertas tenant une torche et une tablette gravée de la date de l'indépendance américaine. Monument néo-classique monumental, elle incarne l'espoir et l'émancipation. Aujourd'hui encore, elle demeure un repère historique et culturel majeur.",
      ticketPrice: 22,
      visitDuration: '2h-3h',
      booking: 'Obligatoire',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:00', end: '16:30' }],
            mardi: [{ start: '09:00', end: '16:30' }],
            mercredi: [{ start: '09:00', end: '16:30' }],
            jeudi: [{ start: '09:00', end: '16:30' }],
            vendredi: [{ start: '09:00', end: '16:30' }],
            samedi: [{ start: '09:00', end: '16:30' }],
            dimanche: [{ start: '09:00', end: '16:30' }],
         },
         note: 'Accès uniquement via ferry (horaires de départ/retour variables). Prévoir large.',
      },
   },
   {
      id: '13',
      cityId: '4',
      name: 'Buckingham Palace',
      image: 'https://cdn-imgix.headout.com/media/images/31a4bf553f447246bf5bd92b00cb1707-12286-london-changing-of-the-guard-tour-with-optional-buckingham-palace-entry-11.jpg',
      city: 'Londres',
      country: 'Royaume-Uni',
      constructionYear: '1703',
      architect: 'William Winde',
      style: 'Néo-classique',
      description:
         "Résidence officielle des souverains britanniques à Londres, Buckingham Palace est un symbole majeur de la monarchie britannique. Construit au début du XVIIIᵉ siècle puis agrandi au fil du temps, il adopte un style néo-classique sobre et monumental. Le palais compte plus de 700 pièces, dont des salons d'apparat utilisés lors de cérémonies officielles et de réceptions d'État. La célèbre relève de la garde attire quotidiennement de nombreux visiteurs. Au-delà de sa fonction résidentielle, Buckingham Palace représente la continuité et la tradition de la Couronne au cœur de la capitale britannique.",
      ticketPrice: 32,
      visitDuration: '1h30-2h30',
      booking: 'Obligatoire',
      accessStatus: 'Accès restreint',
      accessiblePRM: true,
      schedules: {
         type: 'Variable',
         days: {
            lundi: [],
            mardi: [],
            mercredi: [],
            jeudi: [],
            vendredi: [],
            samedi: [],
            dimanche: [],
         },
         note: 'Ouverture au public surtout en été pour les State Rooms (en 2026 : 9 juillet → 27 septembre). Hors saison : seulement certaines dates (visites guidées).',
      },
   },
   {
      id: '14',
      cityId: '4',
      name: 'Tower Bridge',
      image: 'https://cdn.britannica.com/35/156335-050-62245FCA/Tower-Bridge-River-Thames-London.jpg',
      city: 'Londres',
      country: 'Royaume-Uni',
      constructionYear: '1894',
      architect: 'Horace Jones',
      style: 'Néogothique',
      description:
         "Inauguré en 1894, le Tower Bridge est l'un des ponts les plus reconnaissables de Londres. Conçu dans un style néogothique afin de s'harmoniser avec la Tour de Londres voisine, il combine esthétique historique et prouesse technique. Son mécanisme basculant permet aux navires de grande taille de circuler sur la Tamise. Les passerelles supérieures offrent aujourd'hui une vue panoramique sur la ville et retracent l'histoire industrielle du pont. Véritable emblème londonien, il illustre l'ingénierie victorienne et demeure un élément central du paysage urbain.",
      ticketPrice: 12,
      visitDuration: '1h-1h30',
      booking: 'Recommandée',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:30', end: '18:00' }],
            mardi: [{ start: '09:30', end: '18:00' }],
            mercredi: [{ start: '09:30', end: '18:00' }],
            jeudi: [{ start: '09:30', end: '18:00' }],
            vendredi: [{ start: '09:30', end: '18:00' }],
            samedi: [{ start: '09:30', end: '18:00' }],
            dimanche: [{ start: '09:30', end: '18:00' }],
         },
         note: 'Dernière entrée : 17:00.',
      },
   },
   {
      id: '5',
      cityId: '5',
      name: 'Fontaine de Trevi',
      image: 'https://as2.ftcdn.net/v2/jpg/01/21/87/47/1000_F_121874733_ObMVN0dprpejLPmvkQumpLRvxOWOI7sW.jpg',
      city: 'Rome',
      country: 'Italie',
      constructionYear: '1762',
      architect: 'Nicola Salvi',
      style: 'Baroque',
      description:
         "Achevée en 1762, la Fontaine de Trevi est l'un des chefs-d'œuvre du baroque romain. Conçue par Nicola Salvi, elle marque le point d'arrivée de l'ancien aqueduc de l'Acqua Vergine. Son décor spectaculaire représente Neptune sur un char tiré par des chevaux marins, entouré de sculptures allégoriques. La composition théâtrale, les jeux d'eau et la richesse des détails en font un monument particulièrement impressionnant. Selon la tradition, jeter une pièce dans la fontaine garantit un retour à Rome. Elle demeure aujourd'hui l'un des sites les plus visités et photographiés de la capitale italienne.",
      ticketPrice: 0,
      visitDuration: '20-30 min',
      booking: 'Non requis',
      accessStatus: 'Accès libre',
      accessiblePRM: true,
      schedules: {
         type: 'Accès libre',
         days: {
            lundi: [{ start: '00:00', end: '23:59' }],
            mardi: [{ start: '00:00', end: '23:59' }],
            mercredi: [{ start: '00:00', end: '23:59' }],
            jeudi: [{ start: '00:00', end: '23:59' }],
            vendredi: [{ start: '00:00', end: '23:59' }],
            samedi: [{ start: '00:00', end: '23:59' }],
            dimanche: [{ start: '00:00', end: '23:59' }],
         },
         note: 'La place reste accessible. Depuis le 2 fév 2026, l’accès au bord (zone la plus proche) est payant à certaines heures : lun–ven ~11:30–22:00 ; week-end ~09:00–22:00.',
      },
   },
   {
      id: '15',
      cityId: '5',
      name: 'Le Panthéon',
      image: 'https://voyageur-attitude.fr/wp-content/uploads/Le-Pantheon-1024x644.jpg',
      city: 'Rome',
      country: 'Italie',
      constructionYear: '125',
      architect: 'Apollodore de Damas',
      style: 'Antique',
      description:
         "Construit au IIᵉ siècle sous l'empereur Hadrien, le Panthéon de Rome est l'un des monuments antiques les mieux conservés au monde. Dédié à l'ensemble des divinités romaines, il impressionne par son immense coupole en béton coiffée d'un oculus central laissant pénétrer la lumière naturelle. Son portique à colonnes corinthiennes témoigne du génie architectural de l'Antiquité. Transformé en église chrétienne au VIIᵉ siècle, il a ainsi échappé à la destruction. Chef-d'œuvre d'ingénierie antique, le Panthéon continue de fasciner par l'harmonie de ses proportions et sa longévité exceptionnelle.",
      ticketPrice: 5,
      visitDuration: '45-60 min',
      booking: 'Recommandée',
      accessStatus: 'Visitable',
      accessiblePRM: false,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:00', end: '19:00' }],
            mardi: [{ start: '09:00', end: '19:00' }],
            mercredi: [{ start: '09:00', end: '19:00' }],
            jeudi: [{ start: '09:00', end: '19:00' }],
            vendredi: [{ start: '09:00', end: '19:00' }],
            samedi: [{ start: '09:00', end: '19:00' }],
            dimanche: [{ start: '09:00', end: '19:00' }],
         },
         note: 'Dernière entrée ~18:45. Fermé : 1er janvier, 15 août, 25 décembre (et variations possibles lors de célébrations).',
      },
   },
   {
      id: '6',
      cityId: '6',
      name: 'Sagrada Família',
      image: 'https://lelephant-larevue.fr/wp-content/uploads/2018/03/%CE%A3%CE%B1%CE%B3%CF%81%CE%B1%CC%81%CE%B4%CE%B1_%CE%A6%CE%B1%CE%BC%CE%B9%CC%81%CE%BB%CE%B9%CE%B1_2941.jpg',
      city: 'Barcelone',
      country: 'Espagne',
      constructionYear: '1882',
      architect: 'Antoni Gaudí',
      style: 'Modernisme catalan',
      description:
         "Commencée en 1882, la Sagrada Família est l'œuvre monumentale d'Antoni Gaudí et l'un des symboles majeurs de Barcelone. Mélange unique de spiritualité, de nature et d'innovation architecturale, elle incarne le modernisme catalan dans toute sa créativité. Ses façades richement sculptées racontent des épisodes bibliques tandis que l'intérieur, baigné de lumière colorée, évoque une forêt de colonnes élancées. Toujours en construction plus d'un siècle après son lancement, la basilique témoigne d'un projet artistique ambitieux et visionnaire. Classée au patrimoine mondial de l'UNESCO, elle attire des millions de visiteurs chaque année.",
      ticketPrice: 26,
      visitDuration: '1h30-2h',
      booking: 'Obligatoire',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:00', end: '18:00' }],
            mardi: [{ start: '09:00', end: '18:00' }],
            mercredi: [{ start: '09:00', end: '18:00' }],
            jeudi: [{ start: '09:00', end: '18:00' }],
            vendredi: [{ start: '09:00', end: '18:00' }],
            samedi: [{ start: '09:00', end: '18:00' }],
            dimanche: [{ start: '10:30', end: '18:00' }],
         },
         note: 'Horaires saisonniers (différents en mars/oct et avril→sept).',
      },
   },
   {
      id: '16',
      cityId: '6',
      name: 'Parc Güell',
      image: 'https://www.guidesulysse.com/images/destinations/iStock-534846887.jpg',
      city: 'Barcelone',
      country: 'Espagne',
      constructionYear: '1900',
      architect: 'Antoni Gaudí',
      style: 'Modernisme catalan',
      description:
         "Imaginé au début du XXᵉ siècle par Antoni Gaudí, le Parc Güell est un vaste ensemble paysager mêlant architecture et nature. Conçu à l'origine comme un projet résidentiel, il est devenu un parc public emblématique de Barcelone. Ses mosaïques colorées, ses formes ondulantes et ses structures organiques illustrent pleinement le modernisme catalan. La célèbre salamandre en céramique et la terrasse panoramique offrent des points de vue spectaculaires sur la ville. Véritable œuvre d'art à ciel ouvert, le parc reflète la vision poétique et innovante de son architecte.",
      ticketPrice: 10,
      visitDuration: '1h-2h',
      booking: 'Recommandée',
      accessStatus: 'Visitable',
      accessiblePRM: true,
      schedules: {
         type: 'Horaires',
         days: {
            lundi: [{ start: '09:30', end: '18:00' }],
            mardi: [{ start: '09:30', end: '18:00' }],
            mercredi: [{ start: '09:30', end: '18:00' }],
            jeudi: [{ start: '09:30', end: '18:00' }],
            vendredi: [{ start: '09:30', end: '18:00' }],
            samedi: [{ start: '09:30', end: '18:00' }],
            dimanche: [{ start: '09:30', end: '18:00' }],
         },
         note: 'Créneaux de visite (tickets) + plages réservées aux résidents/adhérents (hors visite touristique). Horaires pouvant varier selon périodes.',
      },
   },
]

export const categories = [
   { id: '1', name: 'Musées', icon: '🏛' },
   { id: '2', name: 'Ponts', icon: '🌉' },
   { id: '3', name: 'Religieux', icon: '⛪' },
   { id: '4', name: 'Gratte-ciels', icon: '🏙' },
   { id: '5', name: 'Châteaux & palais', icon: '🏰' },
   { id: '6', name: 'Bâtiments civils', icon: '🏢' },
]
