export const addBuildingDefaultValues = {
   name: '',
   address: '',
   postal_code: '',
   city_id: null,
   categories_id: null,
   image: '',
   construction_year: '',
   architect: '',
   style: '',
   description: '',
   ticket_price: '',
   visit_duration: '',
   booking: '',
   access_status: '',
   accessible_prm: '',
   latitude: '',
   longitude: '',
   schedules: {
      type: '',
      note: '',
      officialHoursUrl: '',
      days: {
         lundi: [],
         mardi: [],
         mercredi: [],
         jeudi: [],
         vendredi: [],
         samedi: [],
         dimanche: [],
      },
   },
}
