export const addBuildingDefaultValues = {
   name: '',
   address: '',
   postal_code: '',
   city_id: null,
   categories_id: null,
   image: '',
   construction_year: '',
   architect: '',
   style: '',
   description: '',
   ticket_price: '',
   visit_duration: '',
   booking: '',
   access_status: '',
   accessible_prm: '',
   latitude: '',
   longitude: '',
   schedules: {
      sameForAllDays: true,
      globalStart: '',
      globalEnd: '',
      type: '',
      note: '',
      officialHoursUrl: '',
      days: {
         lundi: [{ start: '', end: '' }],
         mardi: [{ start: '', end: '' }],
         mercredi: [{ start: '', end: '' }],
         jeudi: [{ start: '', end: '' }],
         vendredi: [{ start: '', end: '' }],
         samedi: [{ start: '', end: '' }],
         dimanche: [{ start: '', end: '' }],
      },
   },
}
